### ISSUE TITLE
Error while extracting images from a rosbag file

### ISSUE THREAD

**Issue by Deepak3994** [valtech/ros_hadoop#13]
Hi guys,

I was trying to implement ros_hadoop. I have also downloaded a rosbag file from udacity github. 
When I opened the rosbag file I found these keys that are present,
![screenshot_2018-08-09 ros-hadoop-practise](https://user-images.githubusercontent.com/20994657/43877844-a69e13ea-9bb9-11e8-8315-88d550453533.png)

Next, when i tried to extract the image from "/center_camera/image_color" this key, I am getting the below error,
![screenshot_2018-08-09 ros-hadoop-practise 1](https://user-images.githubusercontent.com/20994657/43877893-d90b0b9e-9bb9-11e8-8845-f704cf590b5c.png)

Could anyone tell me what actually this is and how to rectify.

**Comment by wiegelmann** [comment]
What exactly is the Udacity file that you try to load?
What version of Python and PIL?
What is len(BytesIO(res[48])) ?

**Comment by Deepak3994** [comment]
I was trying to execute the same codes which was given in the readme.md file in the "valtech/ros_hadoop" github repo.

**Comment by flomader** [comment]
I am experiencing the same issue. I am using Python 2.7 and the Udacity dataset.bag.tar.gz (40GB uncompressed). The image extraction only works on compressed images. When reading not compressed images, the bytearray needs to be converted so that PIL.Image.open understands the format. Any thoughts on how this can be done?

**Comment by autovia-user** [comment]
On most of the systems the original [PIL - Python Image Library](https://en.wikipedia.org/wiki/Python_Imaging_Library) implementation was replaced by a new one, somehow API compatible named Pillow.

- The Pillow implementation (In Linux distributions is typically provided by the python3-imaging package)
    -  Supported [Image File Formats](https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html) Please note that some are write only or even identify only
    - Many of Pillow’s features require external libraries. Please see installation instructions and make sure your system is up to date.

- In the original PIL implementation some of the file formats supported are PPM, PNG, JPEG, GIF, TIFF, and BMP. It is possible to create new decoders for your own file formats. More on the [documentation site](http://www.pythonware.com/library/pil/handbook/)
