### ISSUE TITLE
Is that possible to provide a scala version of tutorial 

### ISSUE THREAD

**Issue by chenxiang-roadstar** [valtech/ros_hadoop#15]
This format is really helpful for processing at scale. But since scala still the best language for spark. Is that possible to provide a scala tutorial version.
Thanks

**Comment by wiegelmann** [comment]
Basically an Scala solution without ROS means effort of reimplementing parts of ROS in Scala. Spark might be Scala/Python but ROS is C++/Python so the glue is Python not Scala.
