### ISSUE TITLE
Example code throws NumberFormatException 

### ISSUE THREAD

**Issue by ps-spark** [valtech/ros_hadoop#23]
Hi Guys,

Thank you for your great work and providing this library to the public. I played around with it but I couldn't run the example code, you provided in the `readme.md`. It took me two days to figure it out, what the problem was. It throws a `NumberFormatException` in the `RosbagInputFormat.getBlockSize()` method:

`context.getConfiguration.get("dfs.blocksize").toLong`

Your configuration does not contain `dfs.blocksize` and the above line cannot cast null to Long.

```
fin = sc.newAPIHadoopFile(
    path =             "hdfs://127.0.0.1:9000/user/root/HMB_4.bag",
    inputFormatClass = "io.autovia.foss.RosbagMapInputFormat",
    keyClass =         "org.apache.hadoop.io.LongWritable",
    valueClass =       "org.apache.hadoop.io.MapWritable",
    conf = {“RosbagInputFormat.chunkIdx”:”/opt/ros_hadoop/master/dist/HMB_4.bag.idx.bin"})
```

Please add the missing parameter to the code example! A default value would be nice, if the parameter is not defined.

**Comment by autovia-user** [comment]
Hi ps-spark,

```dfs.blocksize``` is a standard default HDFS configuration, available also in the latest version. See here [hdfs-default.xml](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml) - search for it.

Please provide the version of your HDFS implementation. It is imperative to have the correct value of the underlying implementation, so do not add it yourself.

**Comment by ps-spark** [comment]
Hi @autovia-user,

OK, I understand now, why it did not work. I'm not using HDFS but S3 with the [Hadoop S3A Connector](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/connecting.html). It basically gives access to S3 as it would be a Hadoop filesystem. So that's the reason, I don't have `dfs.blocksize` .

What would be the recommended value for S3? It's not even block storage. 

I used 4096 and successfully processed Rosbag files directly from S3 with Spark. Really cool :+1:

**Comment by autovia-user** [comment]
Ok, nice. Closing...
